const LOAD_BOOKS = 'LOAD_BOOKS';
const SET_BOOKS = 'SET_BOOKS';
const SET_SEARCH = 'SET_SEARCH';
const SET_SELECTED_BOOK = 'SET_SELECTED_BOOK';
const LOAD_BOOK = 'LOAD_BOOK';
const LOAD_SEARCH = 'LOAD_SEARCH'
const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';
const SET_LIMIT = 'SET_LIMIT';
const SET_TOTAL = 'SET_TOTAL';
const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
const SET_BOOK_IN_BASKET = 'SET_BOOK_IN_BASKET';
const LOAD_BOOKS_IN_BASKET = 'LOAD_BOOKS_IN_BASKET';
const REMOVE_BOOK = 'REMOVE_BOOK'

export {
  LOAD_BOOKS,
  SET_BOOKS,
  SET_SEARCH,
  SET_SELECTED_BOOK,
  LOAD_BOOK,
  SET_SEARCH_RESULTS,
  SET_LIMIT,
  SET_TOTAL,
  SET_CURRENT_PAGE,
  LOAD_SEARCH,
  SET_BOOK_IN_BASKET,
  LOAD_BOOKS_IN_BASKET,
  REMOVE_BOOK
}