const ACTIVATION_SIGN_UP = 'ACTIVATION_SIGN_UP'
const SIGN_UP = 'SIGN_UP'
const SIGN_IN = 'SIGN_IN'
const GET_USER_DATA = 'GET_USER_DATA'
const SET_USER = 'SET_USER'

export {
  ACTIVATION_SIGN_UP,
  SIGN_UP,
  SIGN_IN,
  GET_USER_DATA, 
  SET_USER 
}